### ISSUE TITLE
build: mold-web nix build broken since c866646 (#565) — TS2614 named type import of RailClip from ClipRail.vue

### ISSUE THREAD

**Issue by jamesbrink** [utensils/mold#569]
## Summary

`ceb472a` (PR #568, "feat(desktop): unify sequence authoring into Create") breaks the Nix build of `mold-web` — and therefore `mold` and `mold-desktop`, which depend on it — with a TypeScript error in a test file.

## Error

From `nix build` of the flake at `ceb472a` (x86_64-linux):

```
error: Cannot build '/nix/store/f0bh59hg4n9scig6pwsa0vqcah5zf76g-mold-web-0.10.0.drv'.
       Reason: builder failed with exit code 2.
       > ../ui/components/ClipRail.test.ts:4:15 - error TS2614: Module '"*.vue"' has no exported member 'RailClip'. Did you mean to use 'import RailClip from "*.vue"' instead?
       > Found 1 error.
error: Cannot build '/nix/store/1hxdvm3b5gya9l9frwv4lazy2j2wzj32-mold-0.10.0.drv'.
       Reason: 1 dependency failed.
error: Cannot build '/nix/store/88bfi3ijr1zvcphxn5z13c99zx435y7d-mold-desktop-0.20.2.drv'.
       Reason: 1 dependency failed.
```

Looks like `ClipRail.test.ts` uses a named import (`import { RailClip } from './ClipRail.vue'`) where the module's ambient `*.vue` declaration only exposes a default export, so `tsc` fails during the web bundle build.

## Impact

Flake consumers tracking `main` cannot build any package that depends on `mold-web` at `ceb472a`. Previous commit `5233080` builds fine (we've pinned to it as a workaround).

## Environment

- `nix build github:utensils/mold#default` / `#mold-desktop`, x86_64-linux (NixOS 26.05)

**Comment by jamesbrink** [comment]
Correction after bisecting: the break was introduced in c866646 (#565, "shared sequence kit"), which added `ui/components/ClipRail.vue` and `ClipRail.test.ts` — not #568 as originally reported. `5233080` fails with the identical error; `b231487` (#564) builds fine.

The offending line is:

```ts
// ui/components/ClipRail.test.ts:4
import type { RailClip } from "./ClipRail.vue";
```

`vue-tsc` resolves `.vue` imports via the ambient `*.vue` module declaration (default export only), so the named type import fails under `vue-tsc -b` in the Nix sandbox. Moving the `RailClip` type to a plain `.ts` module (or exporting it from a `<script lang="ts">` block that vue-tsc can see project-wide) should fix it.

**Comment by jamesbrink** [comment]
This builds again as of current main — `nix build github:utensils/mold/315094b9eb2e65647581628b610146ae311c3213#mold-web` succeeds (the ClipRail type import must have been reworked in the sequence-authoring follow-ups). Fine to close from my side.

**Comment by jamesbrink** [comment]
Closing as completed by #570 (5b67a378). The RailClip type now lives in ui/components/types.ts, the test imports it from that plain TypeScript module, and the reporter verified the current-main Nix build succeeds.
