### ISSUE TITLE
build: mold-desktop-web broken since 4234a0d (#661) — TS2722 in SequenceComposer.test.ts fails vue-tsc during build

### ISSUE THREAD

**Issue by jamesbrink** [utensils/mold#670]
## Summary

`4234a0d` (PR #661, "feat(studio): improve sequence source and timeline controls") breaks the Nix build of `mold-desktop-web` (and therefore `mold-desktop`) with a TypeScript error in a test file, reproducible on both x86_64-linux and aarch64-darwin.

## Error

From `vue-tsc -b` during `bun run build:desktop`:

```
src/components/create/SequenceComposer.test.ts:433:11 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

433     await wrapper.vm.importTomlText(toml);
              ~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.
error: script "build" exited with code 1
error: script "build:desktop" exited with code 1
```

## Bisection

- `787762c` (#656) — builds OK
- `4234a0d` (#661) — first bad (last commit to touch `SequenceComposer.test.ts`)
- `a6c850d` (current main HEAD) — still broken

Same failure class as #569: a type error in a `*.test.ts` file that `vue-tsc -b` type-checks as part of the production build. A guard (`wrapper.vm.importTomlText!(...)` or a non-optional typing for the exposed method) — or excluding test files from the build tsconfig — would fix it and prevent the recurrence.

## Environment

- `nix build github:utensils/mold#mold-desktop-web`, x86_64-linux (NixOS 26.05) and aarch64-darwin
- Flake consumers tracking `main` cannot build `mold-desktop` at any commit since #661; we've pinned to `787762c` as a workaround.

**Comment by jamesbrink** [comment]
Reproduced again on hpserver/Plato while deploying Mold `ade6e33583c5e9a5b83b152576c297acc1a86cef` on 2026-08-04.

`nix develop -c deploy-test` reaches `mold-desktop-web-0.20.2`, then fails in `vue-tsc -b` with the same error:

```text
src/components/create/SequenceComposer.test.ts:433:11 - error TS2722: Cannot invoke an object which is possibly undefined.
433     await wrapper.vm.importTomlText(toml);
```

This blocks the full NixOS system closure and therefore deployment of the otherwise updated Mold server. Current Mold `main` (`6136345`) is only one commit ahead and does not appear to include a fix.
